name: Pytest

on:

  # Triggers the workflow on pull requests on master branch

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Get pytest and other requirements
        run: |
          sudo apt-get install python3
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install pytest-cov

      - name: Run pytest
        run: pytest --cov-report xml:$GITHUB_WORKSPACE/coverage.xml
